vim.o.clipboard="unnamedplus"             --Copy paste between vim and everything else
vim.o.incsearch=true
vim.o.guifont="JetBrainsMono\\ Nerd\\ Font\\ Mono:h18"
vim.o.termguicolors=true
vim.o.background="dark"                   --tell vim what the background color looks like
vim.o.shiftwidth=2                        --Change the number of space characters inserted for indentation
vim.o.smarttab=true                       --Makes tabbing smarter will realize you have 2 vs 4
vim.o.expandtab=true                      --Converts tabs to spaces
vim.o.smartindent=true                    --Makes indenting smart
vim.o.autoindent=true                     --Good auto indent
vim.o.laststatus=2                        --Always display the status line
vim.o.number = true
vim.o.backup = false
vim.o.showtabline=2                       --Always show tabs
--vim.o.cursorline=true                   --Enable highlighting of the current line 
vim.o.showmode=false                      --We don't need to see things like -- INSERT -- anymore
vim.wo.signcolumn = "yes"                 -- Always show the signcolumn, otherwise it would shift the text each time
vim.o.mouse = 'a'
vim.o.splitbelow = true                   -- Horizontal splits will automatically be below
vim.o.hidden = true
vim.o.hlsearch = true                     -- highlight all matches on previous search pattern
vim.o.ignorecase = true                   --Ignore case in search pattern
vim.o.undofile = true                     --Enable Persistent undofile
vim.o.updatetime = 300
vim.o.scrolloff = 8
vim.cmd("set nowrap")                     --Disable Line Wrapping
